INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', 36, '2018-01-01');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', 26, '2018-01-02');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', 18, '2018-01-03');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', 28, '2018-01-04');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', 76, '2018-02-01');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', 105, '2018-02-10');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', 24, '2018-02-18');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', 33, '2018-02-28');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', 61, '2018-03-03');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', 44, '2018-03-04');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', 55, '2018-03-05');
INSERT INTO clientes (nombre, apellido, email,edad, create_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', 14, '2018-03-06');